### PR TITLE
Improve sqlite execute

### PR DESCRIPTION
**Pull request by NiklasMerz**
I just added the improvement suggested by @brodybits in issue #1319 .

Travis showed an error with an missing dependency. I removed it as suggested in the issue of the npm repository

### CODE REVIEW

**Comment by gortok** [comment]
I don't see the jscs hint fix in your commits. IS it in this PR?

**Comment by NiklasMerz** [comment]
the jshint fix is in  issue #1329 + pull request.

The build fix in this module is the dead dependency of the module fs.

**Comment by NiklasMerz** [comment]
I removed my change from this PR in favor of PR #1330

**Comment by NiklasMerz** [comment]
closing this to clean the chaos up.

**Pull request closed without merging**
