### PR TITLE
Fixed all apache cordova install commands.

### PR DESCRIPTION
**Pull request by Kurtz1993**

### CODE REVIEW

**Comment by gortok** [comment]
Most of these look great; my question is on this diff:
```
-  cordova plugin add de.appplant.cordova.plugin.local-notification
+ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git
```

Is there a specific reason to target the github repo master repo instead of a published release?

**Comment by Kurtz1993** [comment]
I couldn't fetch the plugin with the ID, but with the repo. That's why I put the repo URL, but I think there's no difference.

**Comment by root-io** [comment]
https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html
Everything will be deprecated the October, 15th.

**Comment by Kurtz1993** [comment]
Thanks for the advice!

**Comment by digitaldrummerj** [comment]
The original documentation was correct for the install locations.  Not sure why it was changed.  I just spent a bunch of time researching why I was getting deprecation warnings following the install commands on the ngCordova docs.

**Pull request merged**
