### PR TITLE
Add $cordovaBeacon plugin

### PR DESCRIPTION
**Pull request by DanailMinchev**
Add iBeacon plugin for https://github.com/petermetz/cordova-plugin-ibeacon

Rebase of https://github.com/driftyco/ng-cordova/pull/857

### CODE REVIEW

**Comment by gortok** [comment]
I think this is great; but it's a bit daunting because there aren't any docs around it. We do have the gh-pages branch; it'd be really, really, really useful if you could put together some examples and docs around how to use this for inclusion in our docs.

**Comment by DanailMinchev** [comment]
Sure, will do in few days and link with new PR, thanks.

**Comment by beauby** [comment]
Cool work! It might be worth splitting it into 2 commits, one for the new plugin, and one for all the cleanup you did. Also, your IDE-generated files arguably do not belong to the `.gitignore` but in your `core.excludesfile`.

**Comment by gortok** [comment]
@DanailMinchev @beauby 's comments are spot on.

**Comment by DanailMinchev** [comment]
@beauby @gortok
Thanks for the comments.

1. The cleanup code was merged by another commit and also if there is a new code coming from `ng-cordova-oauth` submodule it will be added automatically as well. It's better to have separate commits, I will try to separate the new plugin code and generated one.
By the way you can notice this in other PRs as well, that's why I've decided it's common practice.

2. About `.gitignore` : I'm using Jetbrain's IDE and noticed that some of it's files are already included, like ".idea/*", that's why I have added another one "*.iml" (it was generated and should be ignored as well). I think it's better to have common patterns in project's `.gitignore`, because some developers might not have setted up `core.excludesfile` (like me). I can create different commit for this one or maybe another PR for some of https://github.com/github/gitignore
Let me know which one is better.

**Comment by beauby** [comment]
@DanailMinchev First of all, be assured I didn't mean these comments in an offensive way.
1. I understand that other PRs do mix additional functionalities and clean up. However, making separate PRs for this allows for easier reviewing and thus faster merging. Plus it keeps the history tidy.
2. I understand as well that there is already `.idea/` in the `.gitignore`, but I think it should be removed as well, within a clean up PR. The rational behind it is that considering the variety of IDEs/operating systems, and the various files they generate, it would be complicated to maintain a thorough list. The `.gitignore` should be limited to project-specific files.

**Comment by gortok** [comment]
@beauby is correct; we haven't always adhered to it.   We are now because someone brought it up now;  it's an organic thing.  We're really appreciative of your work @DanailMinchev; thank you.

**Comment by DanailMinchev** [comment]
1. @beauby  the comments you did are _not_ offensive in anyway :) ( maybe I did not express myself properly ).
Moreover, it's the opposite: I appreciate your feedback and any comments / fix / improvements are welcome!
I just wanted to clarify my intentions and ask what is preferable for the project style / common practice - because I saw PRs doing the opposite thing and some projects have rules about "less commits per PR".
As I mentioned, I also think and agree that separate commits per feature/change are best practice and I will do the original changes commit and another commit for auto-generating code - much better. Or you mean to drop the generated code at all from the PR? If latest is true, then I'm not sure how it can be tested with "demo" project without creating a new build, that's why it is included in PR.
What is the process here: should I create separate commits with generated code or remove generated code at all from PR? @gortok could you please clarify what's the process for this?

2. @beauby I can see much clearer now the point of removing env specific files and leave only project ones in `.gitignore` - thank you for clarifying this. I will do separate PR for this, please let me know if I done something wrong.

Thanks for the feedback once again @beauby @gortok

**Comment by DanailMinchev** [comment]
@gortok @beauby 

I've submitted the changes as discussed

1. Added documentation in https://github.com/driftyco/ng-cordova/pull/924
2. Separated the plugin and build changes in two commits
3. Created a new PR for `.gitignore`: https://github.com/driftyco/ng-cordova/pull/925

Please let me know if everything is fine.

Thank you!

**Comment by root-io** [comment]
Hey @DanailMinchev awesome job :+1: ! Do you know why I get the error `TypeError: null is not a finite value at Function.BeaconRegion.checkMajorOrMinor` with your example ? I thought the major and minor were optional ?

**Comment by DanailMinchev** [comment]
@root-io 
Thank you for noticing, it's my mistake. I do apologize!
It was stupid copy&paste error from my previous tests, the value to the native plugin should be `undefined` instead of `null`.
I have submitted & rebased the PR, it now works with `null` values as in example.
Please let me know if you have any problems.

Thanks!

**Comment by gortok** [comment]
Thanks for doing this; can you update and re-issue this PR against the `dev-next` branch? I'm happy to include it, but going forward want to put in all features to a dev branch first.

**Comment by DanailMinchev** [comment]
Sure, will do.

**Pull request closed without merging**
