### PR TITLE
Enable options for barcode scanner

### PR DESCRIPTION
**Pull request by fh-seannicholls**
Added config parameter to allow additional parameters to be passed into the barcode scanner compatible with the follow pull request on the barcode scanner source project:

https://github.com/wildabeast/BarcodeScanner/pull/250

### CODE REVIEW

**Comment by pbernasconi** [comment]
Letme know if [your PR for the official plugin](wildabeast/BarcodeScanner#250) gets merged, if so I'd be happy to merge this one!

**Comment by fh-seannicholls** [comment]
Great!

Unfortunately, the [official plugin appears to be abandoned](https://github.com/wildabeast/BarcodeScanner/issues/243), so that may be unlikely.

In the meantime, I'd argue that this PR allows developers to extend the barcode capability in their own projects regardless of the official plugin's contribution.

**Comment by beaubrewer** [comment]
I would like to see this merged as well. I can confirm the "official plugin" appears to be abandoned.

**Comment by fh-seannicholls** [comment]
The official barcode scanner library has a new home, with the above mention changes merged. 

https://github.com/wildabeast/BarcodeScanner/issues/243#issuecomment-87109945

The maintained repo is located at:
https://github.com/phonegap/phonegap-plugin-barcodescanner

**Comment by beaubrewer** [comment]
Awesome! Great to hear the plugin has a new home and it's alive and well!

**Pull request merged**
