### PR TITLE
[$cordovaSQLite] Using db.sqlBatch within insertCollection

### PR DESCRIPTION
**Pull request by shinrox**
So it doesn't create a new transaction for each statement

### CODE REVIEW

**Comment by gortok** [comment]
Please put this against `dev-next`, not master.

**Comment by gortok** [comment]
Also, please don't include any files from dist/*; as those are build artifacts.

**Comment by shinrox** [comment]
sorry, didn't realize it was target to master... I'll fix it

**Comment by gortok** [comment]
Still have the issue with all the changes in dist/*. The changes just need to be done in the plugins/folder; not in the dist/* folder.

**Comment by shinrox** [comment]
created a new PR

**Pull request closed without merging**
