### PR TITLE
Added $cordovaProgress Mock Fix #1126

### LINKED ISSUE #1126: Add progressIndicator $cordovaProgress Mock
I'd like to unit test some $cordovaProgress, that would be nice if had a Mock for it.

http://ngcordova.com/docs/plugins/progressIndicator/

### PR DESCRIPTION
**Pull request by leocaseiro**
Add mock for $cordovaProgress. It'll show console.info which can be used for Browser testing as well.

### CODE REVIEW

**Comment by leocaseiro** [comment]
ping

**Comment by gortok** [comment]
re-issue? We just fixed an issue with our Jasmine/Karma instance and I want to make sure it still builds.

**Comment by gortok** [comment]
turns out if I close and re-open, I can trigger another build through Travis.

TIL.

**Comment by gortok** [comment]
@leocaseiro Can you strip the commit from this branch that changes the ng-cordova /dist files? If we include those changed files, it causes merge issues down the line.

I'll also add something to the contributing.md so this is more apparent to others.

**Comment by leocaseiro** [comment]
Would you like to check it now, @gortok? Is that what I should've done?

**Comment by leocaseiro** [comment]
:beer:

**Pull request merged**
