### PR TITLE
add getFreeDiskSpace function to the file module

### PR DESCRIPTION
**Pull request by nraboy**
Add new getFreeDiskSpace function and appropriate documentation.  This was per request of issue https://github.com/driftyco/ng-cordova/issues/649

### CODE REVIEW

**Comment by nraboy** [comment]
Sweet.  Thanks man!

**Comment by nikolayhg** [comment]
Awesome! Thank you @pbernasconi and @nraboy!

**Comment by ghenry22** [comment]
unfortunately it always returns 0 on iOS on both the simulator and a physical device (testing ios8.1 and 8.3 on ipad, iphone 6, 5, 5c) all return 0.

**Comment by nraboy** [comment]
See this comment:

https://blog.nraboy.com/2015/02/get-available-free-disk-space-using-apache-cordova/#comment-1916276871

It is apparently a bug with Apache Cordova.

Regards,

**Comment by ghenry22** [comment]
I found a few other comments around it in the Cordova Jira as well, If I can fix it I'll submit a pull request and then this should work as expected in ngcordova as well

**Comment by nraboy** [comment]
great :-)

**Comment by ghenry22** [comment]
https://issues.apache.org/jira/browse/CB-6703?focusedCommentId=14617733&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14617733

Tested and submitted, works with ngCordova file as expected with this

**Comment by nraboy** [comment]
Hopefully they approve it

**Comment by ghenry22** [comment]
I can't think of any reason not to, even if it's considered an "undocumented and unsupported" feature it is in the code and broken, it's a single line change to have it working so no chance of breaking anything else.  I moved it to it's own seperate issue and pull request for clarity but it's sitting there ready to merge.

Maybe consider contributing some of your code to the file plugin javascript interface?  Then the code in ngCordova can be simplified and kept consistent with other functions?  You could submit it under the ticket I linked above.  More incentive to merge both then as they deliver a working feature.

**Pull request merged**
