### PR TITLE
Windows 10 Support for AppRate

### PR DESCRIPTION
**Pull request by timothystewart6**
Telling AppRate to use Windows 8 settings is a nice workaround, but we should create its own preference placeholder.  I created a PR to add this setting in AppRate since it uses a different method for determining the Windows 10 platform.
https://github.com/pushandplay/cordova-plugin-apprate/pull/120

### CODE REVIEW

**Comment by timothystewart6** [comment]
If you would rather me only make changes to code without running the `gulp` task, let me know and I can rework this PR.

**Comment by gortok** [comment]
This is great; can you make this against `dev-next` instead of `master`, and don't include any of the build files in the commit?  Feel free to run `gulp jscs`. After you run `gulp build`, you can revert any changes to files in ./dist/*.

**Comment by timothystewart6** [comment]
Sure thing!  On it!

**Comment by gortok** [comment]
Still hoping you'll target this against `dev-next` instead of `master`.

**Comment by timothystewart6** [comment]
This is superseded by https://github.com/driftyco/ng-cordova/pull/1286
Closing.

**Pull request closed without merging**
