### PR TITLE
add plugin insomnia - prevent screen sleep

### PR DESCRIPTION
**Pull request by alexandreetf**
Add support insomnia plugin to ngCordova

### CODE REVIEW

**Comment by pbernasconi** [comment]
Thanks for the PR @alexandreetf! can do you two things:

- Add a comment in the plugin file for `link` and `github`, like for the [other plugins](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/adMob.js#L1-L2)

- Add `'ngCordova.plugins.insomnia'` to the [module.js](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/module.js) file so that is it actually injected as a dependency.

**Comment by alexandreetf** [comment]
Corrected!

**Comment by pbernasconi** [comment]
cheers @alexandreetf

**Comment by phaggood** [comment]
any idea when ngcordova with insomnia will be released?

**Comment by alexandreetf** [comment]
Hi phaggood,

I don't know when it will be release in website (ngcordova.com), but if you download ng-cordova.js already is available.

i only did a contribution.

**Pull request merged**
