### PR TITLE
Added support for cordova.plugins.diagnostic

### PR DESCRIPTION
**Pull request by boboldehampsink**
Added support for cordova.plugins.diagnostic

https://www.npmjs.com/package/cordova.plugins.diagnostic

### CODE REVIEW

**Comment by BrunoCartier** [comment]
This is great :+1: 

But shouldn't the `sqlitePlugin`-related changes be part of another pull-request?

**Comment by boboldehampsink** [comment]
That got automatically built, so I guess someone forgot it before ;-) I can't really remove it without completely removing it from the source. I guess this should be fixed upstream and then pulled in.

**Comment by gortok** [comment]
Yea, I also had an issue with the sql-lite plugin. If you can, rebase your changes off the current state of the `dev-next` branch; and reissue the PR.

**Comment by boboldehampsink** [comment]
A new PR has been openend

**Pull request closed without merging**
