### PR TITLE
Include ng-cordova-oauth as submodule instead of packaging in ng-cordova

### PR DESCRIPTION
**Pull request by nraboy**
So this is a major change, but I did some testing and it seems to work out fine.  I would love to get a second set of eyes on the changes I made.

Essentially, I removed all the oauth code that was already coming from my master https://github.com/nraboy/ng-cordova-oauth repository.  Previously I updated the Ionic repository by copy and pasting all the code from my repository.  It was hard to maintain and I fell behind on keeping them both in sync.

Now, the two repositories are connected via submodules.  When `gulp` is run from the command line, it will update the oauth submodule before building.  It will pull all changes from the master ng-cordova-oauth repo.  Since all development and pull requests for ng-cordova-oauth happen on a development branch, there is little or zero chance of problems with pulling the stable master.

How does this sound?

### CODE REVIEW

**Comment by nraboy** [comment]
Since this is a major change to a heavily used feature of ngCordova, I want to cc @cfjedimaster @pbernasconi @mhartington and @mlynch for review.

Sorry if that came out spammy.  Let me know if there are flaws in my plan.

**Comment by nraboy** [comment]
Hey guys,

I want to put some pressure on this.  Has anyone had a chance to review this concept for ngCordova?

I get too many inquiries to manage regarding the versioning differences between ng-cordova-oauth and ng-cordova.  Time is too short to keep them both up to date which is why I think submodules to my repo is the best option.

Thanks,

cc @mlynch @pbernasconi @mhartington @cfjedimaster @saimon24

**Comment by saimon24** [comment]
It think it's very reasonable to connect your repo as a submodule to ngCordova. 

This is a very important feature many users need, and to keep it updated is really mandatory. People are asking for updates all the time, and every change is more work than it should be.

**Comment by mlynch** [comment]
Thanks @nraboy! Let's see how it goes. I find submodules a pain to work with but for something like this I think it's a good option.

**Comment by nraboy** [comment]
Awesome, thanks for the merge!

Because I added Git related items to the Gulp script, I don't think it will be an issue.  People won't need to worry about manually obtaining the oauth code.  Just build and you're good to go.

I'll keep an eye out if this is causing issues for people.

Thanks,

**Pull request merged**
