### PR TITLE
Add $cordovaProgress.show(message) for Android

### PR DESCRIPTION
**Pull request by nraboy**
@linuxjuggler brought it to my attention that even though the base ProgressIndicator plugin had Android support, it did not exist in ngCordova.  Added the following to ngCordova:

```
$cordovaProgress.show(message)
```

The base plugin has the following craziness:

```
ProgressIndicator.show(_type, _dim, _label, _detail)
```

However, it looks like that is never used anywhere.  The Android function of that only expects a single parameter.

It is important to note that `show(message)` is for Android only.

### CODE REVIEW

**Comment by nraboy** [comment]
@pbernasconi Are you going to be able to merge this request?

Regards,

**Comment by pbernasconi** [comment]
@nraboy Could you rebase your PR, because it's currently unmergable?

**Comment by nraboy** [comment]
@pbernasconi Should be good now :)

**Comment by pbernasconi** [comment]
Thanks!

**Comment by nraboy** [comment]
Any time!

**Pull request merged**
