### PR TITLE
OAuth - use query params for HTTP posts

### PR DESCRIPTION
**Pull request by danieljoppi**
remove $http.defaults.headers.post['Content-Type'] = 'application/x-www-.form-urlencoded';

use query params for HTTP post requests

### CODE REVIEW

**Comment by pbernasconi** [comment]
This looks great. Breaks down the POST and GET a lot better.

@nraboy what's your opinion?

@danieljoppi One thing I've noticed is that the `method` value (eg: `post` and `get`) is not capitalized (`POST`, `GET`) -- does this work?

**Comment by danieljoppi** [comment]
@pbernasconi works

**Comment by nraboy** [comment]
Hi @pbernasconi and @danieljoppi,

I do have some concerns with this.  I forgot which ones, but I believe some of the Oauth providers expected urlencoded values instead of JSON.  Because of this, the ideal way that you mentioned, failed to work.

Have you personally tested the providers that you changed?  If you tested and it works, then it sounds great, but at the moment I am a little skeptical still.

Let me know.

**Comment by danieljoppi** [comment]
@nraboy I have tested with LinkedIn and works fine ... the others providers (I belive ) which is the same thing ..

**Comment by nraboy** [comment]
Up to @pbernasconi if he wants more thorough testing or not.  In theory they should all work fine.  I just remember having issues with a few of them, I don't remember which ones or if they have been since corrected by the provider.

**Comment by pbernasconi** [comment]
I'm going to close this for now. The current solution works, and there isn't a big difference in performance.

**Pull request closed without merging**
