### PR TITLE
Optimized gitignore - ignore only project-specific files

### PR DESCRIPTION
**Pull request by DanailMinchev**
Optimized gitignore - ignore only project-specific files and use global .gitignore for other files (like environment specific & IDEs)

More information:
https://help.github.com/articles/ignoring-files/

Related to:
https://github.com/driftyco/ng-cordova/pull/911

### CODE REVIEW

**Comment by gortok** [comment]
Since .DS_Store was removed, what to do about when that gets included again? Where should that be handled?

**Comment by DanailMinchev** [comment]
Hi @gortok ,

According to [Create a global .gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) you should:

1. create `~/.gitignore_global` with following contents:
```
.DS_Store
```

2. execute command:
```
git config --global core.excludesfile ~/.gitignore_global
```

I removed `.DS_Store`, because it is not project specific file as described & suggested in https://github.com/driftyco/ng-cordova/pull/911#issuecomment-127976614

Thanks

**Comment by gortok** [comment]
I like this, but I'm a little worried about it, so I'll hang on to this for the next release.

**Comment by gortok** [comment]
Also, please issue this PR against `dev-next`.

**Pull request closed without merging**
