### PR TITLE
avoid $q.notify error in media plugin

### PR DESCRIPTION
**Pull request by jesucarr**

### CODE REVIEW

**Comment by bytenik** [comment]
Can this get merged? At the moment the media plugin is useless.

**Comment by gortok** [comment]
@bytenik  It appears that right now the build is broken; so no merges until it's fixed.

**Comment by gortok** [comment]
We had to upgrade our Jasmine instance. Thanks to #1174; it was fixed. Try again?

Sorry about that.

**Comment by gortok** [comment]
turns out if I close and re-open, I can trigger another build through Travis.

TIL.

**Comment by gortok** [comment]
Please strip the dist/ files from the commit and I'll merge.

**Comment by elliotmendiola** [comment]
I fix this in my recent pull request... It's a simple null reference error... I currently use my fixed version in a walkie-talkie feature in my app and it functions beautifully

It should be attached to issue #1204

**Comment by gortok** [comment]
closing as #1205 submitted with stripped /dist files. Thanks for working on this.

**Pull request closed without merging**
