### PR TITLE
Add getbadgenumber() for pushV5

### PR DESCRIPTION
**Pull request by ushu**
All in the title.

I needed this one....

Regards.

### CODE REVIEW

**Comment by AllenConquest** [comment]
When is this going to be merged into master along with #1091? These are both missing from the basic implementation. 

Regards.

**Comment by gortok** [comment]
@AllenConquest This needs to be pointed at dev-next, per the contributing.md file.

@ushu can you point this to dev-next instead of master?

**Comment by AllenConquest** [comment]
I have created a fork from @ushu and pointed it at dev-next. [](https://github.com/AllenConquest/ng-cordova)

**Comment by gortok** [comment]
@AllenConquest Awesome.  Next step is to go to that repo's page and click "Issue Pull Request"; and it'll walk you through what you need to do next .https://help.github.com/articles/using-pull-requests/

**Pull request closed without merging**
