### PR TITLE
Wrapper for cordova googlplus plugin 

### PR DESCRIPTION
**Pull request by sachinB94**
This pull requests consist of the wrapper for cordova-plugin-googleplus (https://github.com/EddyVerbruggen/cordova-plugin-googleplus).

### CODE REVIEW

**Comment by gortok** [comment]
We currently use this one: https://github.com/EddyVerbruggen/cordova-plugin-googleplus and the wrapper is here: 

https://github.com/driftyco/ng-cordova/blob/master/src/plugins/googlePlus.js How does your wrapper differ?

**Comment by sachinB94** [comment]
They differ in their logins. The more I look at it, I see that it only
supports a single parameter in login, i.e., iosKey. I don't know why the
developer did this, but it doesn't support all the nice parameters as the
cordova-googleplus login.

**Comment by gortok** [comment]
@sachinB94  The better way to handle this; since both of your wrappers rely on the same underlying plugin, would be for you to submit a PR that patches the existing wrapper with the different things you mention, instead of creating a whole new one.

**Comment by sachinB94** [comment]
Agreed. I'll write a patch for the existing google plus wrapper, and submit pull request.

**Pull request closed without merging**
