### PR TITLE
Add $cordovaBeacon plugin

### PR DESCRIPTION
**Pull request by DanailMinchev**
Add iBeacon plugin for https://github.com/petermetz/cordova-plugin-ibeacon

### CODE REVIEW

**Comment by nickfrandsen** [comment]
+1

**Comment by nickfrandsen** [comment]
Anyone have any idea when this is being merged in?

**Comment by gortok** [comment]
Please update, rebase, and re-issue this PR. There are conflicts currently.

**Comment by DanailMinchev** [comment]
@gortok 
Done in https://github.com/driftyco/ng-cordova/pull/911

Thanks

**Pull request closed without merging**
