### PR TITLE
watchPosition should call notify, not resolve

### PR DESCRIPTION
**Pull request by byronigoe**
watchPosition returns a promise which issues updates to the notify function

### CODE REVIEW

**Comment by gortok** [comment]
This should target Dev-next, and you only made the change to the mocks file. Did you mean to make it to the plugin file as well?

**Comment by byronigoe** [comment]
The plugin file is correctly calling notify(). Only the mock was wrong. I don't know how to have a PR target a branch.

It's a one-line change. Perhaps it would be better for you to make the change yourself.

**Comment by gortok** [comment]
No time to learn like the present: In your PR, you can change the branch using this: 

https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by byronigoe** [comment]
Okay. Ready to merge.

**Pull request merged**
