### PR TITLE
Add $cordovaBeacon documentation

### PR DESCRIPTION
**Pull request by DanailMinchev**
Added $cordovaBeacon documentation for https://github.com/driftyco/ng-cordova/pull/911

### CODE REVIEW

**Comment by gortok** [comment]
Thanks for doing this; my only question is around the extensive use of attaching to `$rootScope`; I haven't used this plugin wrapper in particular, but it doesn't seem like it *has* to be that way; nor would that be the preferred method.

Does this plugin require that? Or was it done for expediency?

**Comment by DanailMinchev** [comment]
@gortok 

I'll be happy to improve it, but I'm not sure how ..
The plugin does not require `$rootScope` in particular, but I used it to globally broadcast events - `$rootScope.$broadcast`, I am not sure how to do it without `$rootScope` globally ...
Also, not every event is broadcasted - it depends how are you using the plugin (only for monitoring `startMonitoringForRegion` + ranging `startRangingBeaconsInRegion` - `$cordovaBeacon:didStartMonitoringForRegion`, `$cordovaBeacon:didDetermineStateForRegion`, `$cordovaBeacon:didRangeBeaconsInRegion` are fired)
Could you please give me an example, so I can refactor it?

I have checked other plugins and used them as an example for my implementation (they all use `$rootScope`):
- https://github.com/driftyco/ng-cordova/blob/master/src/plugins/batteryStatus.js
- https://github.com/driftyco/ng-cordova/blob/master/src/plugins/inappbrowser.js
- https://github.com/driftyco/ng-cordova/blob/master/src/plugins/keyboard.js
- https://github.com/driftyco/ng-cordova/blob/master/src/plugins/localNotification.js
- https://github.com/driftyco/ng-cordova/blob/master/src/plugins/network.js
- https://github.com/driftyco/ng-cordova/blob/master/src/plugins/push.js

Please let me know how to do the global events without `$rootScope` and I will refactor all other plugins as well.

Thank you for your suggestions in advance!

**Comment by gortok** [comment]
The reason why I bring up rootScope is that anything that relies on Angular 1.x will potentially have to change for ngCordova2 (which won't be dependent on Angular).

**Comment by DanailMinchev** [comment]
@gortok 

Yes, I suppose there will be:
- Angular 1.x - Ionic Framework 1.x - ngCordova 1.x (current implementation)
- Angular 2.x - Ionic Framework 2.x - ngCordova 2 - plain ES6/TypeScript (future implementation)
and they both will have to be maintained as long as Ionic Framework 1.x / ngCordova 1.x are supported.

It will be good to migrate all the plugins, once https://github.com/driftyco/ng-cordova/tree/v2/src is ready.

Thanks for the merge!

Just to confirm: I can see that it is live now and we have broken link / 404 error (https://github.com/driftyco/ng-cordova/blob/master/src/plugins/beacon.js) on page http://ngcordova.com/docs/plugins/beacon/ , because https://github.com/driftyco/ng-cordova/pull/937 is not merged yet.

**Pull request merged**
