### PR TITLE
Fix oauth and add several more providers

### PR DESCRIPTION
**Pull request by nraboy**
Add fix for the latest version of the InAppBrowser plugin and Apache Cordova 5.0.  Also add a few more oauth providers to the mix.

### CODE REVIEW

**Comment by nraboy** [comment]
This pull request will resolve the following issue tickets:

https://github.com/driftyco/ng-cordova/issues/809
https://github.com/driftyco/ng-cordova/issues/783
https://github.com/driftyco/ng-cordova/issues/774

**Comment by nraboy** [comment]
Thanks!

**Comment by manudefrutosvila** [comment]
Hi, as I mentioned on ng-cordova-oauth https://github.com/nraboy/ng-cordova-oauth/issues/57

The release of ng-cordova v0.1.17-alpha is behind 10 commits of master that solves the inappbrowser not found issue. Could be possible to make a new release to finally fix that?

Thanks!

**Comment by nraboy** [comment]
Hey @manudefrutosvila,

Just like I said on my repository, I have no control on how or when Ionic decides to tag their versions.  Unless you can convince them to add a new tag and more frequently, I suggest you just use the master branch.

Regards,

**Pull request merged**
