### PR TITLE
Wikitude cordova plugin added

### PR DESCRIPTION
**Pull request by yailPeralta**
Hi how are you? I don't work for wikitude but I needed a better way to use wikitude in ionic for a personal project and thought it might be great to share with everyone. 
Regards

### CODE REVIEW

**Comment by gortok** [comment]
This looks great; can you run this PR against dev-next instead of master?

**Comment by yailPeralta** [comment]
thanks, yes, no problem!

**Comment by gortok** [comment]
It's still pointing to master.

**Comment by gortok** [comment]
Same issue as your other PR; I didn't realize you had just copied the script into the dist/ folder without the appropriate files being made in the src/plugins folder.

**Pull request closed without merging**
