### PR TITLE
created mock of cordovaInAppBrowser

### PR DESCRIPTION
**Pull request by francesco-strazzullo**
If you use cordovaInAppBrowser on your application, you cannot launch e2e tests with ngCordovaMocks. I've created an empty stub for this service in the ngCordovaMocks module, in this way we have no problem bootstrapping the application in the test enviroment. Otherwise we encounter a "service not found" problem.

### CODE REVIEW

**Comment by lorenzomassacci** [comment]
+1

**Comment by slash-84** [comment]
+1

**Comment by adellava** [comment]
+1

**Comment by gortok** [comment]
Can you squash these down into one commit and re-issue PR? I like this; there are just a lot of commits here.

**Comment by francesco-strazzullo** [comment]
Ok I will do it right away

**Comment by francesco-strazzullo** [comment]
@gortok you can find the new pull request here

**Pull request closed without merging**
