### PR TITLE
fixed depreciated vibrate plugin functions

### PR DESCRIPTION
**Pull request by ihadeed**

### CODE REVIEW

**Comment by gortok** [comment]
Build fails. Run Jscs and JSHint?

**Comment by ihadeed** [comment]
Does the test environment have the latest plugins installed?

The build error saying that navigator.vibrate is undefined there for navigator.vibrate() isn't a function ...
According to the latest plugin docs it is a function. Works fine when I test that method on an Ionic App.

Ref: https://github.com/apache/cordova-plugin-vibration

**Comment by ihadeed** [comment]
I did another commit but I will make a pull request once the build issue has been resolved.

Added a cancel vibration method that implements the new way ( navigator.vibrate(0) ) ... Just to keep some of the old code running

**Comment by gortok** [comment]
We had to upgrade our Jasmine instance. Thanks to #1174; it was fixed. Try again? And please target dev-next.

**Pull request closed without merging**
