### PR TITLE
Switch mode network mock

### PR DESCRIPTION
**Pull request by francesco-strazzullo**
In previous version of $cordovaNetwork mock you cannot test the switch to offline mode and viceversa. I've added two methods that will do that launching the right events through the rootscope.

### CODE REVIEW

**Comment by pbernasconi** [comment]
@francesco-strazzullo thanks for the PR - however would you mind removing the `build` files from this PR? It causes future problems for merging PRs, so we generally ask that a PR only includes the changes  that belong in this feat/fix.

**Comment by francesco-strazzullo** [comment]
Ok I'll remove the build files right away

**Comment by francesco-strazzullo** [comment]
@pbernasconi I've removed the dist files but I can't figure out why the build is failed. I have all green tests on my machine.

**Comment by francesco-strazzullo** [comment]
@pbernasconi I've removed the dist files but I can't figure out why the build is failed. I have all green tests on my machine.

**Comment by gortok** [comment]
We had to upgrade our Jasmine instance. Thanks to #1174; it was fixed. Try again?

**Comment by gortok** [comment]
turns out if I close and re-open, I can trigger another build through Travis. 

TIL.

**Pull request merged**
